package com.poker
 
import com.poker.PokerController.Game;
 
rule "New Game"
    when
        currentGame : Game( gameState == Game.NEW_GAME, currentGameState : gameState )
    then
        System.out.println("New Game");
        currentGame.newGame();
        currentGame.setGameState( Game.NEW_HAND );
        update( currentGame );
end

rule "New Hand"
    when
        currentGame : Game( gameState == Game.NEW_HAND, currentGameState : gameState )
    then
        System.out.println( "New Hand" );
        currentGame.newHand();
        currentGame.setCurrentBet(currentGame.getSmallBlind());
        currentGame.setGameState( Game.PREFLOP );
        update( currentGame );
end

rule "Pre-Flop; Player Turn;"
    when
        currentGame : Game( gameState == Game.PREFLOP && turn == Game.PLAYER, currentGameState : gameState )
    then
        System.out.println( "Pre Flop - Player Turn" );
        currentGame.playerBet(currentGame.getCurrentBet());
        update( currentGame );
end

rule "Pre-Flop; Agent Turn;"
    when
        currentGame : Game( gameState == Game.PREFLOP && turn == Game.AGENT, currentGameState : gameState )
    then
        System.out.println( "Pre Flop - Agent Turn" );
        currentGame.agentBet(currentGame.getCurrentBet());
        update( currentGame );
end

rule "Flop"
    when
        currentGame : Game( gameState == Game.FLOPDEAL, currentGameState : gameState )
    then
        currentGame.dealBoardCard();
        currentGame.dealBoardCard();
        currentGame.dealBoardCard();
        currentGame.printBoardCards();
        currentGame.setGameState(Game.FLOP);
        update( currentGame );
end


rule "Flop; Player Turn;"
    when
        currentGame : Game( gameState == Game.FLOP && turn == Game.PLAYER, currentGameState : gameState )
    then
        System.out.println( "Flop - Player Turn" );
        currentGame.playerBet(currentGame.getCurrentBet());
        update( currentGame );
end

rule "Flop; Agent Turn;"
    when
        currentGame : Game( gameState == Game.FLOP && turn == Game.AGENT, currentGameState : gameState )
    then
        System.out.println( "Flop - Agent Turn" );
        currentGame.agentBet(currentGame.getCurrentBet());
        update( currentGame );
end

rule "Turn"
    when
        currentGame : Game( gameState == Game.TURNDEAL, currentGameState : gameState )
    then
        currentGame.dealBoardCard();
        currentGame.printBoardCards();
        currentGame.setGameState(Game.TURN);
        update( currentGame );
end

rule "Turn; Player Turn;"
    when
        currentGame : Game( gameState == Game.TURN && turn == Game.PLAYER, currentGameState : gameState )
    then
        System.out.println( "Turn - Player Turn" );
        currentGame.playerBet(currentGame.getCurrentBet());
        update( currentGame );
end

rule "Turn; Agent Turn;"
    when
        currentGame : Game( gameState == Game.TURN && turn == Game.AGENT, currentGameState : gameState )
    then
        System.out.println( "Turn - Agent Turn" );
        currentGame.agentBet(currentGame.getCurrentBet());
        update( currentGame );
end

rule "River"
    when
        currentGame : Game( gameState == Game.RIVERDEAL, currentGameState : gameState )
    then
        currentGame.dealBoardCard();
        currentGame.printBoardCards();
        currentGame.setGameState(Game.RIVER);
        update( currentGame );
end

rule "River; Player Turn;"
    when
        currentGame : Game( gameState == Game.RIVER && turn == Game.PLAYER, currentGameState : gameState )
    then
        System.out.println( "River - Player Turn" );
        currentGame.playerBet(currentGame.getCurrentBet());
        update( currentGame );
end

rule "River; Agent Turn;"
    when
        currentGame : Game( gameState == Game.RIVER && turn == Game.AGENT, currentGameState : gameState )
    then
        System.out.println( "River - Agent Turn" );
        currentGame.agentBet(currentGame.getCurrentBet());
        update( currentGame );
end

rule "Showdown"
    when
        currentGame : Game( gameState == Game.SHOWDOWN, currentGameState : gameState )
    then
        System.out.println( "Showdown" );

        update( currentGame );
end