package com.poker
 
import com.poker.PokerController.Game;
 
rule "New Game"
    when
        currentGame : Game( gameState == Game.NEW_GAME, currentGameState : gameState )
    then
        System.out.println("New Game");
        currentGame.newGame();
        currentGame.setGameState( Game.NEW_HAND );
        update( currentGame );
end

rule "New Hand"
    when
        currentGame : Game( gameState == Game.NEW_HAND, currentGameState : gameState )
    then
        System.out.println( "New Hand" );
        currentGame.newHand();
        currentGame.setGameState( Game.PREFLOP );
        update( currentGame );
end

rule "Pre-Flop; Player Turn; Invalid Bet"
    when
        Game( gameState == Game.PREFLOP && turn = Game.Player, currentGameState : gameState )
    then
        System.out.println( "Pre Flop - Player Turn" );
end
